/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DashboardApiLogsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DashboardApiLogsApiTests : IDisposable
    {
        private DashboardApiLogsApi instance;

        public DashboardApiLogsApiTests()
        {
            instance = new DashboardApiLogsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DashboardApiLogsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DashboardApiLogsApi
            //Assert.IsType(typeof(DashboardApiLogsApi), instance, "instance is a DashboardApiLogsApi");
        }

        
        /// <summary>
        /// Test GetdashboardApiLogs
        /// </summary>
        [Fact]
        public void GetdashboardApiLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string where = null;
            //string sort = null;
            //int? page = null;
            //int? maxResults = null;
            //var response = instance.GetdashboardApiLogs(where, sort, page, maxResults);
            //Assert.IsType<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test GetdashboardApiLogsItem
        /// </summary>
        [Fact]
        public void GetdashboardApiLogsItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string dashboardApiLogsId = null;
            //var response = instance.GetdashboardApiLogsItem(dashboardApiLogsId);
            //Assert.IsType<DashboardApiLogs> (response, "response is DashboardApiLogs");
        }
        
        /// <summary>
        /// Test PatchdashboardApiLogsItem
        /// </summary>
        [Fact]
        public void PatchdashboardApiLogsItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string dashboardApiLogsId = null;
            //string ifMatch = null;
            //DashboardApiLogs dashboardApiLogs = null;
            //instance.PatchdashboardApiLogsItem(dashboardApiLogsId, ifMatch, dashboardApiLogs);
            
        }
        
        /// <summary>
        /// Test PostdashboardApiLogs
        /// </summary>
        [Fact]
        public void PostdashboardApiLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DashboardApiLogs dashboardApiLogs = null;
            //instance.PostdashboardApiLogs(dashboardApiLogs);
            
        }
        
        /// <summary>
        /// Test PutdashboardApiLogsItem
        /// </summary>
        [Fact]
        public void PutdashboardApiLogsItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string dashboardApiLogsId = null;
            //string ifMatch = null;
            //DashboardApiLogs dashboardApiLogs = null;
            //instance.PutdashboardApiLogsItem(dashboardApiLogsId, ifMatch, dashboardApiLogs);
            
        }
        
    }

}
