/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TenantsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TenantsApiTests : IDisposable
    {
        private TenantsApi instance;

        public TenantsApiTests()
        {
            instance = new TenantsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TenantsApi
            //Assert.IsType(typeof(TenantsApi), instance, "instance is a TenantsApi");
        }

        
        /// <summary>
        /// Test Gettenants
        /// </summary>
        [Fact]
        public void GettenantsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string where = null;
            //string sort = null;
            //int? page = null;
            //int? maxResults = null;
            //var response = instance.Gettenants(where, sort, page, maxResults);
            //Assert.IsType<InlineResponse20014> (response, "response is InlineResponse20014");
        }
        
        /// <summary>
        /// Test GettenantsItem
        /// </summary>
        [Fact]
        public void GettenantsItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantsId = null;
            //var response = instance.GettenantsItem(tenantsId);
            //Assert.IsType<Tenants> (response, "response is Tenants");
        }
        
        /// <summary>
        /// Test PatchtenantsItem
        /// </summary>
        [Fact]
        public void PatchtenantsItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantsId = null;
            //string ifMatch = null;
            //Tenants tenants = null;
            //instance.PatchtenantsItem(tenantsId, ifMatch, tenants);
            
        }
        
        /// <summary>
        /// Test Posttenants
        /// </summary>
        [Fact]
        public void PosttenantsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Tenants tenants = null;
            //instance.Posttenants(tenants);
            
        }
        
        /// <summary>
        /// Test PuttenantsItem
        /// </summary>
        [Fact]
        public void PuttenantsItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantsId = null;
            //string ifMatch = null;
            //Tenants tenants = null;
            //instance.PuttenantsItem(tenantsId, ifMatch, tenants);
            
        }
        
    }

}
