/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOrganizationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>Organizations</returns>
        Organizations GetorganizationsItem (string organizationsId);

        /// <summary>
        /// Retrieves a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>ApiResponse of Organizations</returns>
        ApiResponse<Organizations> GetorganizationsItemWithHttpInfo (string organizationsId);
        /// <summary>
        /// Retrieves one or more orgs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>InlineResponse2008</returns>
        InlineResponse2008 Getorgs (string where = null, string sort = null, int? page = null, int? maxResults = null);

        /// <summary>
        /// Retrieves one or more orgs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>ApiResponse of InlineResponse2008</returns>
        ApiResponse<InlineResponse2008> GetorgsWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null);
        /// <summary>
        /// Updates a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns></returns>
        void PatchorganizationsItem (string organizationsId, string ifMatch, Organizations organizations);

        /// <summary>
        /// Updates a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PatchorganizationsItemWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations);
        /// <summary>
        /// Stores one or more orgs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns></returns>
        void Postorgs (Organizations organizations);

        /// <summary>
        /// Stores one or more orgs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostorgsWithHttpInfo (Organizations organizations);
        /// <summary>
        /// Replaces a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns></returns>
        void PutorganizationsItem (string organizationsId, string ifMatch, Organizations organizations);

        /// <summary>
        /// Replaces a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PutorganizationsItemWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOrganizationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>Task of Organizations</returns>
        System.Threading.Tasks.Task<Organizations> GetorganizationsItemAsync (string organizationsId);

        /// <summary>
        /// Retrieves a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>Task of ApiResponse (Organizations)</returns>
        System.Threading.Tasks.Task<ApiResponse<Organizations>> GetorganizationsItemAsyncWithHttpInfo (string organizationsId);
        /// <summary>
        /// Retrieves one or more orgs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of InlineResponse2008</returns>
        System.Threading.Tasks.Task<InlineResponse2008> GetorgsAsync (string where = null, string sort = null, int? page = null, int? maxResults = null);

        /// <summary>
        /// Retrieves one or more orgs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse2008)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2008>> GetorgsAsyncWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null);
        /// <summary>
        /// Updates a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PatchorganizationsItemAsync (string organizationsId, string ifMatch, Organizations organizations);

        /// <summary>
        /// Updates a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PatchorganizationsItemAsyncWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations);
        /// <summary>
        /// Stores one or more orgs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostorgsAsync (Organizations organizations);

        /// <summary>
        /// Stores one or more orgs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostorgsAsyncWithHttpInfo (Organizations organizations);
        /// <summary>
        /// Replaces a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PutorganizationsItemAsync (string organizationsId, string ifMatch, Organizations organizations);

        /// <summary>
        /// Replaces a organizations document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PutorganizationsItemAsyncWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOrganizationsApi : IOrganizationsApiSync, IOrganizationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OrganizationsApi : IOrganizationsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OrganizationsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OrganizationsApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OrganizationsApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public OrganizationsApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieves a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>Organizations</returns>
        public Organizations GetorganizationsItem (string organizationsId)
        {
             Org.OpenAPITools.Client.ApiResponse<Organizations> localVarResponse = GetorganizationsItemWithHttpInfo(organizationsId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>ApiResponse of Organizations</returns>
        public Org.OpenAPITools.Client.ApiResponse< Organizations > GetorganizationsItemWithHttpInfo (string organizationsId)
        {
            // verify the required parameter 'organizationsId' is set
            if (organizationsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizationsId' when calling OrganizationsApi->GetorganizationsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (organizationsId != null)
                requestOptions.PathParameters.Add("organizationsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(organizationsId)); // path parameter

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get< Organizations >("/orgs/{organizationsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetorganizationsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>Task of Organizations</returns>
        public async System.Threading.Tasks.Task<Organizations> GetorganizationsItemAsync (string organizationsId)
        {
             Org.OpenAPITools.Client.ApiResponse<Organizations> localVarResponse = await GetorganizationsItemAsyncWithHttpInfo(organizationsId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <returns>Task of ApiResponse (Organizations)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Organizations>> GetorganizationsItemAsyncWithHttpInfo (string organizationsId)
        {
            // verify the required parameter 'organizationsId' is set
            if (organizationsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizationsId' when calling OrganizationsApi->GetorganizationsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (organizationsId != null)
                requestOptions.PathParameters.Add("organizationsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(organizationsId)); // path parameter

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<Organizations>("/orgs/{organizationsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetorganizationsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves one or more orgs 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>InlineResponse2008</returns>
        public InlineResponse2008 Getorgs (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
             Org.OpenAPITools.Client.ApiResponse<InlineResponse2008> localVarResponse = GetorgsWithHttpInfo(where, sort, page, maxResults);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves one or more orgs 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>ApiResponse of InlineResponse2008</returns>
        public Org.OpenAPITools.Client.ApiResponse< InlineResponse2008 > GetorgsWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (where != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "where", where))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (sort != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sort", sort))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (page != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (maxResults != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "max_results", maxResults))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get< InlineResponse2008 >("/orgs", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Getorgs", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves one or more orgs 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of InlineResponse2008</returns>
        public async System.Threading.Tasks.Task<InlineResponse2008> GetorgsAsync (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
             Org.OpenAPITools.Client.ApiResponse<InlineResponse2008> localVarResponse = await GetorgsAsyncWithHttpInfo(where, sort, page, maxResults);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves one or more orgs 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse2008)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<InlineResponse2008>> GetorgsAsyncWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (where != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "where", where))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (sort != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sort", sort))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (page != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (maxResults != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "max_results", maxResults))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<InlineResponse2008>("/orgs", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Getorgs", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Updates a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns></returns>
        public void PatchorganizationsItem (string organizationsId, string ifMatch, Organizations organizations)
        {
             PatchorganizationsItemWithHttpInfo(organizationsId, ifMatch, organizations);
        }

        /// <summary>
        /// Updates a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PatchorganizationsItemWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations)
        {
            // verify the required parameter 'organizationsId' is set
            if (organizationsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizationsId' when calling OrganizationsApi->PatchorganizationsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling OrganizationsApi->PatchorganizationsItem");

            // verify the required parameter 'organizations' is set
            if (organizations == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizations' when calling OrganizationsApi->PatchorganizationsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (organizationsId != null)
                requestOptions.PathParameters.Add("organizationsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(organizationsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = organizations;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Patch<Object>("/orgs/{organizationsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PatchorganizationsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Updates a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PatchorganizationsItemAsync (string organizationsId, string ifMatch, Organizations organizations)
        {
             await PatchorganizationsItemAsyncWithHttpInfo(organizationsId, ifMatch, organizations);

        }

        /// <summary>
        /// Updates a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PatchorganizationsItemAsyncWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations)
        {
            // verify the required parameter 'organizationsId' is set
            if (organizationsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizationsId' when calling OrganizationsApi->PatchorganizationsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling OrganizationsApi->PatchorganizationsItem");

            // verify the required parameter 'organizations' is set
            if (organizations == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizations' when calling OrganizationsApi->PatchorganizationsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (organizationsId != null)
                requestOptions.PathParameters.Add("organizationsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(organizationsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = organizations;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PatchAsync<Object>("/orgs/{organizationsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PatchorganizationsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Stores one or more orgs. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns></returns>
        public void Postorgs (Organizations organizations)
        {
             PostorgsWithHttpInfo(organizations);
        }

        /// <summary>
        /// Stores one or more orgs. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PostorgsWithHttpInfo (Organizations organizations)
        {
            // verify the required parameter 'organizations' is set
            if (organizations == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizations' when calling OrganizationsApi->Postorgs");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            requestOptions.Data = organizations;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Post<Object>("/orgs", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Postorgs", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Stores one or more orgs. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostorgsAsync (Organizations organizations)
        {
             await PostorgsAsyncWithHttpInfo(organizations);

        }

        /// <summary>
        /// Stores one or more orgs. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PostorgsAsyncWithHttpInfo (Organizations organizations)
        {
            // verify the required parameter 'organizations' is set
            if (organizations == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizations' when calling OrganizationsApi->Postorgs");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            requestOptions.Data = organizations;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PostAsync<Object>("/orgs", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Postorgs", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Replaces a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns></returns>
        public void PutorganizationsItem (string organizationsId, string ifMatch, Organizations organizations)
        {
             PutorganizationsItemWithHttpInfo(organizationsId, ifMatch, organizations);
        }

        /// <summary>
        /// Replaces a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PutorganizationsItemWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations)
        {
            // verify the required parameter 'organizationsId' is set
            if (organizationsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizationsId' when calling OrganizationsApi->PutorganizationsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling OrganizationsApi->PutorganizationsItem");

            // verify the required parameter 'organizations' is set
            if (organizations == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizations' when calling OrganizationsApi->PutorganizationsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (organizationsId != null)
                requestOptions.PathParameters.Add("organizationsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(organizationsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = organizations;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Put<Object>("/orgs/{organizationsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PutorganizationsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Replaces a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PutorganizationsItemAsync (string organizationsId, string ifMatch, Organizations organizations)
        {
             await PutorganizationsItemAsyncWithHttpInfo(organizationsId, ifMatch, organizations);

        }

        /// <summary>
        /// Replaces a organizations document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="organizations">A organizations or list of organizations documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PutorganizationsItemAsyncWithHttpInfo (string organizationsId, string ifMatch, Organizations organizations)
        {
            // verify the required parameter 'organizationsId' is set
            if (organizationsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizationsId' when calling OrganizationsApi->PutorganizationsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling OrganizationsApi->PutorganizationsItem");

            // verify the required parameter 'organizations' is set
            if (organizations == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'organizations' when calling OrganizationsApi->PutorganizationsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (organizationsId != null)
                requestOptions.PathParameters.Add("organizationsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(organizationsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = organizations;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PutAsync<Object>("/orgs/{organizationsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PutorganizationsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
