/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRegionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves one or more regions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>InlineResponse2009</returns>
        InlineResponse2009 Getregions (string where = null, string sort = null, int? page = null, int? maxResults = null);

        /// <summary>
        /// Retrieves one or more regions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>ApiResponse of InlineResponse2009</returns>
        ApiResponse<InlineResponse2009> GetregionsWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null);
        /// <summary>
        /// Retrieves a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>Regions</returns>
        Regions GetregionsItem (string regionsId);

        /// <summary>
        /// Retrieves a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>ApiResponse of Regions</returns>
        ApiResponse<Regions> GetregionsItemWithHttpInfo (string regionsId);
        /// <summary>
        /// Updates a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns></returns>
        void PatchregionsItem (string regionsId, string ifMatch, Regions regions);

        /// <summary>
        /// Updates a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PatchregionsItemWithHttpInfo (string regionsId, string ifMatch, Regions regions);
        /// <summary>
        /// Stores one or more regions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns></returns>
        void Postregions (Regions regions);

        /// <summary>
        /// Stores one or more regions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostregionsWithHttpInfo (Regions regions);
        /// <summary>
        /// Replaces a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns></returns>
        void PutregionsItem (string regionsId, string ifMatch, Regions regions);

        /// <summary>
        /// Replaces a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PutregionsItemWithHttpInfo (string regionsId, string ifMatch, Regions regions);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRegionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves one or more regions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of InlineResponse2009</returns>
        System.Threading.Tasks.Task<InlineResponse2009> GetregionsAsync (string where = null, string sort = null, int? page = null, int? maxResults = null);

        /// <summary>
        /// Retrieves one or more regions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse2009)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2009>> GetregionsAsyncWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null);
        /// <summary>
        /// Retrieves a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>Task of Regions</returns>
        System.Threading.Tasks.Task<Regions> GetregionsItemAsync (string regionsId);

        /// <summary>
        /// Retrieves a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>Task of ApiResponse (Regions)</returns>
        System.Threading.Tasks.Task<ApiResponse<Regions>> GetregionsItemAsyncWithHttpInfo (string regionsId);
        /// <summary>
        /// Updates a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PatchregionsItemAsync (string regionsId, string ifMatch, Regions regions);

        /// <summary>
        /// Updates a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PatchregionsItemAsyncWithHttpInfo (string regionsId, string ifMatch, Regions regions);
        /// <summary>
        /// Stores one or more regions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostregionsAsync (Regions regions);

        /// <summary>
        /// Stores one or more regions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostregionsAsyncWithHttpInfo (Regions regions);
        /// <summary>
        /// Replaces a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PutregionsItemAsync (string regionsId, string ifMatch, Regions regions);

        /// <summary>
        /// Replaces a regions document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PutregionsItemAsyncWithHttpInfo (string regionsId, string ifMatch, Regions regions);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRegionsApi : IRegionsApiSync, IRegionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RegionsApi : IRegionsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RegionsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RegionsApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RegionsApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RegionsApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieves one or more regions 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>InlineResponse2009</returns>
        public InlineResponse2009 Getregions (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
             Org.OpenAPITools.Client.ApiResponse<InlineResponse2009> localVarResponse = GetregionsWithHttpInfo(where, sort, page, maxResults);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves one or more regions 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>ApiResponse of InlineResponse2009</returns>
        public Org.OpenAPITools.Client.ApiResponse< InlineResponse2009 > GetregionsWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (where != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "where", where))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (sort != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sort", sort))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (page != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (maxResults != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "max_results", maxResults))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get< InlineResponse2009 >("/regions", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Getregions", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves one or more regions 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of InlineResponse2009</returns>
        public async System.Threading.Tasks.Task<InlineResponse2009> GetregionsAsync (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
             Org.OpenAPITools.Client.ApiResponse<InlineResponse2009> localVarResponse = await GetregionsAsyncWithHttpInfo(where, sort, page, maxResults);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves one or more regions 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse2009)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<InlineResponse2009>> GetregionsAsyncWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (where != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "where", where))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (sort != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sort", sort))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (page != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (maxResults != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "max_results", maxResults))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<InlineResponse2009>("/regions", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Getregions", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>Regions</returns>
        public Regions GetregionsItem (string regionsId)
        {
             Org.OpenAPITools.Client.ApiResponse<Regions> localVarResponse = GetregionsItemWithHttpInfo(regionsId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>ApiResponse of Regions</returns>
        public Org.OpenAPITools.Client.ApiResponse< Regions > GetregionsItemWithHttpInfo (string regionsId)
        {
            // verify the required parameter 'regionsId' is set
            if (regionsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regionsId' when calling RegionsApi->GetregionsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (regionsId != null)
                requestOptions.PathParameters.Add("regionsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(regionsId)); // path parameter

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get< Regions >("/regions/{regionsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetregionsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>Task of Regions</returns>
        public async System.Threading.Tasks.Task<Regions> GetregionsItemAsync (string regionsId)
        {
             Org.OpenAPITools.Client.ApiResponse<Regions> localVarResponse = await GetregionsItemAsyncWithHttpInfo(regionsId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <returns>Task of ApiResponse (Regions)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Regions>> GetregionsItemAsyncWithHttpInfo (string regionsId)
        {
            // verify the required parameter 'regionsId' is set
            if (regionsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regionsId' when calling RegionsApi->GetregionsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (regionsId != null)
                requestOptions.PathParameters.Add("regionsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(regionsId)); // path parameter

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<Regions>("/regions/{regionsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetregionsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Updates a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns></returns>
        public void PatchregionsItem (string regionsId, string ifMatch, Regions regions)
        {
             PatchregionsItemWithHttpInfo(regionsId, ifMatch, regions);
        }

        /// <summary>
        /// Updates a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PatchregionsItemWithHttpInfo (string regionsId, string ifMatch, Regions regions)
        {
            // verify the required parameter 'regionsId' is set
            if (regionsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regionsId' when calling RegionsApi->PatchregionsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling RegionsApi->PatchregionsItem");

            // verify the required parameter 'regions' is set
            if (regions == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regions' when calling RegionsApi->PatchregionsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (regionsId != null)
                requestOptions.PathParameters.Add("regionsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(regionsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = regions;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Patch<Object>("/regions/{regionsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PatchregionsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Updates a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PatchregionsItemAsync (string regionsId, string ifMatch, Regions regions)
        {
             await PatchregionsItemAsyncWithHttpInfo(regionsId, ifMatch, regions);

        }

        /// <summary>
        /// Updates a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PatchregionsItemAsyncWithHttpInfo (string regionsId, string ifMatch, Regions regions)
        {
            // verify the required parameter 'regionsId' is set
            if (regionsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regionsId' when calling RegionsApi->PatchregionsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling RegionsApi->PatchregionsItem");

            // verify the required parameter 'regions' is set
            if (regions == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regions' when calling RegionsApi->PatchregionsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (regionsId != null)
                requestOptions.PathParameters.Add("regionsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(regionsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = regions;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PatchAsync<Object>("/regions/{regionsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PatchregionsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Stores one or more regions. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns></returns>
        public void Postregions (Regions regions)
        {
             PostregionsWithHttpInfo(regions);
        }

        /// <summary>
        /// Stores one or more regions. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PostregionsWithHttpInfo (Regions regions)
        {
            // verify the required parameter 'regions' is set
            if (regions == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regions' when calling RegionsApi->Postregions");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            requestOptions.Data = regions;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Post<Object>("/regions", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Postregions", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Stores one or more regions. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostregionsAsync (Regions regions)
        {
             await PostregionsAsyncWithHttpInfo(regions);

        }

        /// <summary>
        /// Stores one or more regions. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PostregionsAsyncWithHttpInfo (Regions regions)
        {
            // verify the required parameter 'regions' is set
            if (regions == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regions' when calling RegionsApi->Postregions");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            requestOptions.Data = regions;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PostAsync<Object>("/regions", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Postregions", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Replaces a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns></returns>
        public void PutregionsItem (string regionsId, string ifMatch, Regions regions)
        {
             PutregionsItemWithHttpInfo(regionsId, ifMatch, regions);
        }

        /// <summary>
        /// Replaces a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PutregionsItemWithHttpInfo (string regionsId, string ifMatch, Regions regions)
        {
            // verify the required parameter 'regionsId' is set
            if (regionsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regionsId' when calling RegionsApi->PutregionsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling RegionsApi->PutregionsItem");

            // verify the required parameter 'regions' is set
            if (regions == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regions' when calling RegionsApi->PutregionsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (regionsId != null)
                requestOptions.PathParameters.Add("regionsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(regionsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = regions;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Put<Object>("/regions/{regionsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PutregionsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Replaces a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PutregionsItemAsync (string regionsId, string ifMatch, Regions regions)
        {
             await PutregionsItemAsyncWithHttpInfo(regionsId, ifMatch, regions);

        }

        /// <summary>
        /// Replaces a regions document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regionsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="regions">A regions or list of regions documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PutregionsItemAsyncWithHttpInfo (string regionsId, string ifMatch, Regions regions)
        {
            // verify the required parameter 'regionsId' is set
            if (regionsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regionsId' when calling RegionsApi->PutregionsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling RegionsApi->PutregionsItem");

            // verify the required parameter 'regions' is set
            if (regions == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'regions' when calling RegionsApi->PutregionsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (regionsId != null)
                requestOptions.PathParameters.Add("regionsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(regionsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = regions;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PutAsync<Object>("/regions/{regionsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PutregionsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
