/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITenantsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves one or more tenants
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>InlineResponse20014</returns>
        InlineResponse20014 Gettenants (string where = null, string sort = null, int? page = null, int? maxResults = null);

        /// <summary>
        /// Retrieves one or more tenants
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>ApiResponse of InlineResponse20014</returns>
        ApiResponse<InlineResponse20014> GettenantsWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null);
        /// <summary>
        /// Retrieves a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>Tenants</returns>
        Tenants GettenantsItem (string tenantsId);

        /// <summary>
        /// Retrieves a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>ApiResponse of Tenants</returns>
        ApiResponse<Tenants> GettenantsItemWithHttpInfo (string tenantsId);
        /// <summary>
        /// Updates a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns></returns>
        void PatchtenantsItem (string tenantsId, string ifMatch, Tenants tenants);

        /// <summary>
        /// Updates a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PatchtenantsItemWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants);
        /// <summary>
        /// Stores one or more tenants.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns></returns>
        void Posttenants (Tenants tenants);

        /// <summary>
        /// Stores one or more tenants.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PosttenantsWithHttpInfo (Tenants tenants);
        /// <summary>
        /// Replaces a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns></returns>
        void PuttenantsItem (string tenantsId, string ifMatch, Tenants tenants);

        /// <summary>
        /// Replaces a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PuttenantsItemWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITenantsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves one or more tenants
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of InlineResponse20014</returns>
        System.Threading.Tasks.Task<InlineResponse20014> GettenantsAsync (string where = null, string sort = null, int? page = null, int? maxResults = null);

        /// <summary>
        /// Retrieves one or more tenants
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse20014)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse20014>> GettenantsAsyncWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null);
        /// <summary>
        /// Retrieves a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>Task of Tenants</returns>
        System.Threading.Tasks.Task<Tenants> GettenantsItemAsync (string tenantsId);

        /// <summary>
        /// Retrieves a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>Task of ApiResponse (Tenants)</returns>
        System.Threading.Tasks.Task<ApiResponse<Tenants>> GettenantsItemAsyncWithHttpInfo (string tenantsId);
        /// <summary>
        /// Updates a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PatchtenantsItemAsync (string tenantsId, string ifMatch, Tenants tenants);

        /// <summary>
        /// Updates a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PatchtenantsItemAsyncWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants);
        /// <summary>
        /// Stores one or more tenants.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PosttenantsAsync (Tenants tenants);

        /// <summary>
        /// Stores one or more tenants.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PosttenantsAsyncWithHttpInfo (Tenants tenants);
        /// <summary>
        /// Replaces a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PuttenantsItemAsync (string tenantsId, string ifMatch, Tenants tenants);

        /// <summary>
        /// Replaces a tenants document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PuttenantsItemAsyncWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITenantsApi : ITenantsApiSync, ITenantsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TenantsApi : ITenantsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TenantsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TenantsApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TenantsApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TenantsApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieves one or more tenants 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>InlineResponse20014</returns>
        public InlineResponse20014 Gettenants (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
             Org.OpenAPITools.Client.ApiResponse<InlineResponse20014> localVarResponse = GettenantsWithHttpInfo(where, sort, page, maxResults);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves one or more tenants 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>ApiResponse of InlineResponse20014</returns>
        public Org.OpenAPITools.Client.ApiResponse< InlineResponse20014 > GettenantsWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (where != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "where", where))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (sort != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sort", sort))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (page != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (maxResults != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "max_results", maxResults))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get< InlineResponse20014 >("/tenants", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Gettenants", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves one or more tenants 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of InlineResponse20014</returns>
        public async System.Threading.Tasks.Task<InlineResponse20014> GettenantsAsync (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {
             Org.OpenAPITools.Client.ApiResponse<InlineResponse20014> localVarResponse = await GettenantsAsyncWithHttpInfo(where, sort, page, maxResults);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves one or more tenants 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="where">the filters query parameter (ex.: {\&quot;number\&quot;: 10}) (optional)</param>
        /// <param name="sort">the sort query parameter (ex.: \&quot;city,-lastname\&quot;) (optional)</param>
        /// <param name="page">the pages query parameter (optional)</param>
        /// <param name="maxResults">the max results query parameter (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse20014)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<InlineResponse20014>> GettenantsAsyncWithHttpInfo (string where = null, string sort = null, int? page = null, int? maxResults = null)
        {

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (where != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "where", where))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (sort != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "sort", sort))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (page != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (maxResults != null)
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "max_results", maxResults))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<InlineResponse20014>("/tenants", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Gettenants", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>Tenants</returns>
        public Tenants GettenantsItem (string tenantsId)
        {
             Org.OpenAPITools.Client.ApiResponse<Tenants> localVarResponse = GettenantsItemWithHttpInfo(tenantsId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>ApiResponse of Tenants</returns>
        public Org.OpenAPITools.Client.ApiResponse< Tenants > GettenantsItemWithHttpInfo (string tenantsId)
        {
            // verify the required parameter 'tenantsId' is set
            if (tenantsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenantsId' when calling TenantsApi->GettenantsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (tenantsId != null)
                requestOptions.PathParameters.Add("tenantsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tenantsId)); // path parameter

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Get< Tenants >("/tenants/{tenantsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GettenantsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Retrieves a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>Task of Tenants</returns>
        public async System.Threading.Tasks.Task<Tenants> GettenantsItemAsync (string tenantsId)
        {
             Org.OpenAPITools.Client.ApiResponse<Tenants> localVarResponse = await GettenantsItemAsyncWithHttpInfo(tenantsId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <returns>Task of ApiResponse (Tenants)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Tenants>> GettenantsItemAsyncWithHttpInfo (string tenantsId)
        {
            // verify the required parameter 'tenantsId' is set
            if (tenantsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenantsId' when calling TenantsApi->GettenantsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (tenantsId != null)
                requestOptions.PathParameters.Add("tenantsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tenantsId)); // path parameter

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<Tenants>("/tenants/{tenantsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GettenantsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Updates a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns></returns>
        public void PatchtenantsItem (string tenantsId, string ifMatch, Tenants tenants)
        {
             PatchtenantsItemWithHttpInfo(tenantsId, ifMatch, tenants);
        }

        /// <summary>
        /// Updates a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PatchtenantsItemWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants)
        {
            // verify the required parameter 'tenantsId' is set
            if (tenantsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenantsId' when calling TenantsApi->PatchtenantsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling TenantsApi->PatchtenantsItem");

            // verify the required parameter 'tenants' is set
            if (tenants == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenants' when calling TenantsApi->PatchtenantsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (tenantsId != null)
                requestOptions.PathParameters.Add("tenantsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tenantsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = tenants;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Patch<Object>("/tenants/{tenantsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PatchtenantsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Updates a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PatchtenantsItemAsync (string tenantsId, string ifMatch, Tenants tenants)
        {
             await PatchtenantsItemAsyncWithHttpInfo(tenantsId, ifMatch, tenants);

        }

        /// <summary>
        /// Updates a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PatchtenantsItemAsyncWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants)
        {
            // verify the required parameter 'tenantsId' is set
            if (tenantsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenantsId' when calling TenantsApi->PatchtenantsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling TenantsApi->PatchtenantsItem");

            // verify the required parameter 'tenants' is set
            if (tenants == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenants' when calling TenantsApi->PatchtenantsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (tenantsId != null)
                requestOptions.PathParameters.Add("tenantsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tenantsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = tenants;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PatchAsync<Object>("/tenants/{tenantsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PatchtenantsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Stores one or more tenants. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns></returns>
        public void Posttenants (Tenants tenants)
        {
             PosttenantsWithHttpInfo(tenants);
        }

        /// <summary>
        /// Stores one or more tenants. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PosttenantsWithHttpInfo (Tenants tenants)
        {
            // verify the required parameter 'tenants' is set
            if (tenants == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenants' when calling TenantsApi->Posttenants");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            requestOptions.Data = tenants;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Post<Object>("/tenants", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Posttenants", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Stores one or more tenants. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PosttenantsAsync (Tenants tenants)
        {
             await PosttenantsAsyncWithHttpInfo(tenants);

        }

        /// <summary>
        /// Stores one or more tenants. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PosttenantsAsyncWithHttpInfo (Tenants tenants)
        {
            // verify the required parameter 'tenants' is set
            if (tenants == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenants' when calling TenantsApi->Posttenants");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            requestOptions.Data = tenants;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PostAsync<Object>("/tenants", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("Posttenants", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Replaces a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns></returns>
        public void PuttenantsItem (string tenantsId, string ifMatch, Tenants tenants)
        {
             PuttenantsItemWithHttpInfo(tenantsId, ifMatch, tenants);
        }

        /// <summary>
        /// Replaces a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PuttenantsItemWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants)
        {
            // verify the required parameter 'tenantsId' is set
            if (tenantsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenantsId' when calling TenantsApi->PuttenantsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling TenantsApi->PuttenantsItem");

            // verify the required parameter 'tenants' is set
            if (tenants == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenants' when calling TenantsApi->PuttenantsItem");

            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (tenantsId != null)
                requestOptions.PathParameters.Add("tenantsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tenantsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = tenants;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = this.Client.Put<Object>("/tenants/{tenantsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PuttenantsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        /// Replaces a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PuttenantsItemAsync (string tenantsId, string ifMatch, Tenants tenants)
        {
             await PuttenantsItemAsyncWithHttpInfo(tenantsId, ifMatch, tenants);

        }

        /// <summary>
        /// Replaces a tenants document 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantsId"></param>
        /// <param name="ifMatch">Current value of the _etag field</param>
        /// <param name="tenants">A tenants or list of tenants documents</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PuttenantsItemAsyncWithHttpInfo (string tenantsId, string ifMatch, Tenants tenants)
        {
            // verify the required parameter 'tenantsId' is set
            if (tenantsId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenantsId' when calling TenantsApi->PuttenantsItem");

            // verify the required parameter 'ifMatch' is set
            if (ifMatch == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'ifMatch' when calling TenantsApi->PuttenantsItem");

            // verify the required parameter 'tenants' is set
            if (tenants == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tenants' when calling TenantsApi->PuttenantsItem");


            Org.OpenAPITools.Client.RequestOptions requestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] @contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (tenantsId != null)
                requestOptions.PathParameters.Add("tenantsId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tenantsId)); // path parameter
            if (ifMatch != null)
                requestOptions.HeaderParameters.Add("If-Match", Org.OpenAPITools.Client.ClientUtils.ParameterToString(ifMatch)); // header parameter
            requestOptions.Data = tenants;

            // authentication (ApiKeyHeaderAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                requestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (ApiKeyQueryAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                foreach (var kvp in Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "api_key", this.Configuration.GetApiKeyWithPrefix("api_key")))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }

            // make the HTTP request

            var response = await this.AsynchronousClient.PutAsync<Object>("/tenants/{tenantsId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("PuttenantsItem", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
