/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2009
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2009Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2009
        //private InlineResponse2009 instance;

        public InlineResponse2009Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2009
            //instance = new InlineResponse2009();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2009
        /// </summary>
        [Fact]
        public void InlineResponse2009InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2009
            //Assert.IsInstanceOfType<InlineResponse2009> (instance, "variable 'instance' is a InlineResponse2009");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
