/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OrganizationDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganizationDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganizationDetails
        //private OrganizationDetails instance;

        public OrganizationDetailsTests()
        {
            // TODO uncomment below to create an instance of OrganizationDetails
            //instance = new OrganizationDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationDetails
        /// </summary>
        [Fact]
        public void OrganizationDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrganizationDetails
            //Assert.IsInstanceOfType<OrganizationDetails> (instance, "variable 'instance' is a OrganizationDetails");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'ContactType'
        /// </summary>
        [Fact]
        public void ContactTypeTest()
        {
            // TODO unit test for the property 'ContactType'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'SubscriptionEndDateTime'
        /// </summary>
        [Fact]
        public void SubscriptionEndDateTimeTest()
        {
            // TODO unit test for the property 'SubscriptionEndDateTime'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
