/* 
 * Metacore IOT Object Storage API
 *
 * Metacore IOT Core Services
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Tenants
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tenants
        //private Tenants instance;

        public TenantsTests()
        {
            // TODO uncomment below to create an instance of Tenants
            //instance = new Tenants();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tenants
        /// </summary>
        [Fact]
        public void TenantsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Tenants
            //Assert.IsInstanceOfType<Tenants> (instance, "variable 'instance' is a Tenants");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'SubscriptionKey'
        /// </summary>
        [Fact]
        public void SubscriptionKeyTest()
        {
            // TODO unit test for the property 'SubscriptionKey'
        }
        /// <summary>
        /// Test the property 'SubscriptionLimit'
        /// </summary>
        [Fact]
        public void SubscriptionLimitTest()
        {
            // TODO unit test for the property 'SubscriptionLimit'
        }

    }

}
